"""Init

Revision ID: 0e9387ffcb06
Revises: 
Create Date: 2026-06-26 23:42:37.181936
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '0e9387ffcb06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('monthly_credit_grant', sa.Integer(), nullable=False),
    sa.Column('max_output_resolution', sa.String(length=20), nullable=False),
    sa.Column('price_cents_monthly', sa.Integer(), nullable=False),
    sa.Column('concurrent_jobs_limit', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("plan_tier IN ('free', 'starter', 'pro', 'enterprise')", name='ck_workspaces_plan_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('credit_balances',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('last_refilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_credit_balance_non_negative'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_workspace', 'users', ['workspace_id'], unique=False)
    op.create_table('image_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('raw_s3_key', sa.String(length=512), nullable=False),
    sa.Column('raw_width', sa.Integer(), nullable=True),
    sa.Column('raw_height', sa.Integer(), nullable=True),
    sa.Column('raw_file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'MASKING', 'MASKED', 'CLEANING', 'UPSCALING', 'GENERATING_BG', 'PROCESSING', 'COMPLETED', 'FAILED', name='image_status', create_constraint=True), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failed_step', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('mask_s3_key', sa.String(length=512), nullable=True),
    sa.Column('cleaned_s3_key', sa.String(length=512), nullable=True),
    sa.Column('upscaled_s3_key', sa.String(length=512), nullable=True),
    sa.Column('final_s3_key', sa.String(length=512), nullable=True),
    sa.Column('cdn_url', sa.String(length=512), nullable=True),
    sa.Column('background_preset', sa.String(length=50), nullable=True),
    sa.Column('output_aspect_ratio', sa.String(length=10), nullable=True),
    sa.Column('output_resolution', sa.String(length=20), nullable=True),
    sa.Column('inngest_run_id', sa.String(length=255), nullable=True),
    sa.Column('credits_charged', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_inngest_run', 'image_assets', ['inngest_run_id'], unique=False)
    op.create_index('idx_assets_workspace_status', 'image_assets', ['workspace_id', 'status'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('compute_weight_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("reason IN ('monthly_grant', 'generation_charge', 'generation_refund', 'manual_adjustment', 'purchase')", name='ck_ledger_reason'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_assets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_workspace', 'credit_ledger', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ledger_workspace', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index('idx_assets_workspace_status', table_name='image_assets')
    op.drop_index('idx_assets_inngest_run', table_name='image_assets')
    op.drop_table('image_assets')
    op.drop_index('idx_users_workspace', table_name='users')
    op.drop_table('users')
    op.drop_table('credit_balances')
    op.drop_table('workspaces')
    op.drop_table('subscription_tiers')
    # ### end Alembic commands ###
