"""Add analysis_json and variants_json to ImageAsset

Revision ID: 92d24b768c90
Revises: 0e9387ffcb06
Create Date: 2026-06-27 11:07:23.269409
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '92d24b768c90'
down_revision: Union[str, None] = '0e9387ffcb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('analysis_json', sa.JSON(), nullable=True))
    op.add_column('image_assets', sa.Column('variants_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_assets', 'variants_json')
    op.drop_column('image_assets', 'analysis_json')
    # ### end Alembic commands ###
